import Head from 'next/head'
import { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux'
import styles from '../styles/Home.module.css'
import FormContainer from '../helpers/form'
import LandingPage from './landing-page';
import { fetchposts } from '../store/actions/postAction';

export default function Home() {

  const dispatch = useDispatch();
  const {posts} = useSelector(state=>state.post)
  // const post = useSelector(state=>state.post.posts)


  useEffect(() => {
    dispatch(fetchposts())
  },[])
  useEffect(() => {
    console.log("posts",posts);
  },[posts])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <FormContainer />
        </div>
      </main>
    </div>
  )
}
