version: "3.8"
services:
  db:
    image: postgres:15.4
    environment:
    - POSTGRES_USER=$DB_USER
    - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
    - $DB_PORT:$DB_PORT
    volumes:
    - ./postgresql/db:/var/lib/postgresql/data
    restart: always
    command: -p $DB_PORT
  api:
    depends_on:
      - db
    build: ./
    environment:
      - NODE_ENV=$API_NODE_ENV
      - PORT=$API_PORT
      - PGHOST=db
      - PGPORT=$DB_PORT
      - PGUSER=$DB_USER
      - PGPASSWORD=$DB_PASSWORD
      - PGDATABASE=$DB_NAME
    ports:
      - $API_PORT:$API_PORT
    volumes:
      - ./:/app
      - /app/node_modules
  ui:
    build: ./next
    environment:
      - NODE_ENV=$UI_NODE_ENV
      - PORT=$UI_PORT
      - REACT_APP_API_HOST
    ports:
      - $UI_PORT:$UI_PORT
    volumes:
      - ./next:/app
      - /app/node_modules
    stdin_open: true